{"name": "test_State", "status": "failed", "statusDetails": {"message": "datatest.ValidationError: does not satisfy `int` (5339 differences): [\n    Invalid('AK'),\n    Invalid('AK'),\n    Invalid('AK'),\n    Invalid('AK'),\n    Invalid('AK'),\n    Invalid('AK'),\n    Invalid('AK'),\n    Invalid('AK'),\n    ...\n\n...Full output truncated, use '-vv' to show", "trace": "df =       Account_Num                      Facility Name  ...              Hospital Type              Hospital Ownership\n0...      I-70 COMMUNITY HOSPITAL  ...  Critical Access Hospitals                     Proprietary\n\n[5339 rows x 10 columns]\n\n    def test_State(df):\n>       dt.validate(df['State'],int)\nE       datatest.ValidationError: does not satisfy `int` (5339 differences): [\nE           Invalid('AK'),\nE           Invalid('AK'),\nE           Invalid('AK'),\nE           Invalid('AK'),\nE           Invalid('AK'),\nE           Invalid('AK'),\nE           Invalid('AK'),\nE           Invalid('AK'),\nE           ...\nE       \nE       ...Full output truncated, use '-vv' to show\n\ncsvfilecheck.py:46: ValidationError"}, "start": 1630685823852, "stop": 1630685823866, "uuid": "5664ceef-16cb-4b00-82d3-d5915cd3f642", "historyId": "257e29af672a9e2cc39b5c748a982739", "testCaseId": "c1ff543c9a8254f53a19903cd48c11c6", "fullName": "csvfilecheck#test_State", "labels": [{"name": "suite", "value": "csvfilecheck"}, {"name": "host", "value": "DOA-DOIT-CONSL1"}, {"name": "thread", "value": "21296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "csvfilecheck"}]}